site_name: HUME - Mixed Graph Estimation

repo_url: https://github.com/konstantingoe/mixed-gm

theme:
  name: material
  locale: en

extra:
  version:
    default: latest
    provider: mike

plugins:
  - mkdocstrings
  - mike:
      canonical_version: latest

nav:
  - index.md
  - reference.md
